#pragma once

#define SCREEN_HEIGHT 750
#define SCREEN_WIDTH 450
#define WINDOW_TITLE "Road Rumble"

#define PLAYER_WIDTH 71
#define PLAYER_HEIGHT 140
#define TAXI_WIDTH 71
#define TAXI_HEIGHT 138

#define BUTTON_WIDTH 170
#define BUTTON_HEIGHT 85
#define S_BUTTON_WH 43
#define MENU_WIDTH 335
#define MENU_HEIGHT 335
#define EXIT_MENU_WIDTH 16
#define EXIT_MENU_HEIGHT 15
#define BUTTON_MENU_SIZE 5
#define BUTTON_MENU_RESUME_SIZE 5
#define BUTTON_MENU_DIE_SIZE 3
#define BUTTON_STATES_SIZE 3
#define SOUND_EFFECT_SIZE 8

#define ENERGY_WIDTH 21
#define ENERGY_HEIGHT 37
#define TRAFFIC_LIGHT_WIDTH 83
#define TRAFFIC_LIGHT_HEIGHT 288
#define TITLE_WIDTH 275
#define TITLE_HEIGHT 180
#define SLIDE_WIDTH 26
#define SLIDE_HEIGHT 32
#define SCORE_HEIGHT 70
#define BORDER_LEFT 77
#define BORDER_RIGHT 304
#define SLIDE_UPPER_BORDER_X 346
#define SLIDE_BOTTOM_BORDER_X 186
#define SLIDE1_UPPER_BORDER_Y 301
#define SLIDE1_BOTTOM_BORDER_Y 233
#define SLIDE2_UPPER_BORDER_Y 381
#define SLIDE2_BOTTOM_BORDER_Y 313
#define SLIDE3_UPPER_BORDER_Y 459
#define SLIDE3_BOTTOM_BORDER_Y 391

#define SPEED 2
#define SOUND_VOLUME 87
#define EASY_SPEED 5
#define NORMAL_SPEED 7
#define HARD_SPEED 9
#define EASY_MODE 400
#define NORMAL_MODE 300
#define HARD_MODE 150

#define EXPLOSION_SPRITE_SIZE 66
#define PLAYER_SPRITE_SIZE 6
#define ROAD_SPRITE_SIZE 30
#define ITEM_SPRITE_SIZE 36
#define MOVING_SPRITE_SIZE 6
#define EXPLOSION_WIDTH 96
#define EXPLOSION_HEIGHT 92
#define FUEL_WIDTH 186
#define FUEL_HEIGHT 48

#define default_X 153
#define ORIGIN_X 153
#define HIGHWAY_WIDTH 800
#define HIGHWAY_HEIGHT 800
#define LANE_WIDTH 76
#define OBJECT_SIZE 3
#define ENEMIES_SIZE 3
