#pragma once

#define SCREEN_HEIGHT 750
#define SCREEN_WIDTH 450
#define WINDOW_TITLE "Car Race"
#define PLAYER_WIDTH 71
#define PLAYER_HEIGHT 140
#define BUTTON_WIDTH 170
#define BUTTON_HEIGHT 85
#define S_BUTTON_WH 43
#define ENERGY_WIDTH 21
#define ENERGY_HEIGHT 37
#define TRAFFIC_LIGHT_WIDTH 83
#define TRAFFIC_LIGHT_HEIGHT 288
#define TITLE_WIDTH 275
#define TITLE_HEIGHT 180
#define SLIDE_WIDTH 26
#define SLIDE_HEIGHT 32
#define SOUND_VOLUME 87
#define TAXI_WIDTH 71
#define TAXI_HEIGHT 138
#define EXIT_MENU_WIDTH 16
#define EXIT_MENU_HEIGHT 15
#define speed 2
#define default_X 153
#define MENU_WIDTH 335
#define MENU_HEIGHT 335
#define HIGHWAY_WIDTH 800
#define HIGHWAY_HEIGHT 800
